# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  heroku: circleci/heroku@1.2.6
  node: circleci/node@4.2.1
  cypress: cypress-io/cypress@1.27.0
workflows:
  test-and-deploy:
    jobs:
      - node/test
      # - heroku/deploy-via-git:
      #     filters:
      #       branches:
      #         only:
      #           - master
      #     requires:
      #       - node/test
