# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  heroku: circleci/heroku@1.2.6
  node: circleci/node@4.2.1
  cypress: cypress-io/cypress@1.27.0

jobs:
  deploy:
    executor:
      name: heroku/default
    steps:
      - checkout
      - setup_remote_docker
      - heroku/install
      - node/install
      - heroku/check-authentication
      - node/install-packages
      - run:
          command: npm run build
      - heroku/push-docker-image:
          process-types: web
          recursive: true
      - heroku/release-docker-image:
          process-types: web
workflows:
  test-and-deploy:
    jobs:
      - node/test
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - node/test
